apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: calfornia-housing-pipeline-
  annotations: {pipelines.kubeflow.org/kfp_sdk_version: 1.8.22, pipelines.kubeflow.org/pipeline_compilation_time: '2023-05-20T19:45:53.051806',
    pipelines.kubeflow.org/pipeline_spec: '{"description": "Calfornia Housing Pipeline",
      "name": "Calfornia Housing Pipeline"}'}
  labels: {pipelines.kubeflow.org/kfp_sdk_version: 1.8.22}
spec:
  entrypoint: calfornia-housing-pipeline
  templates:
  - name: calfornia-housing-pipeline
    dag:
      tasks:
      - {name: preprocess-data, template: preprocess-data}
  - name: preprocess-data
    container:
      args: []
      image: samyumobi99/rp:latest
    outputs:
      artifacts:
      - {name: preprocess-data-x_test, path: /app/x_test.npy}
      - {name: preprocess-data-x_train, path: /app/x_train.npy}
      - {name: preprocess-data-y_test, path: /app/y_test.npy}
      - {name: preprocess-data-y_train, path: /app/y_train.npy}
    metadata:
      labels:
        pipelines.kubeflow.org/kfp_sdk_version: 1.8.22
        pipelines.kubeflow.org/pipeline-sdk-type: kfp
        pipelines.kubeflow.org/enable_caching: "true"
  arguments:
    parameters: []
  serviceAccountName: pipeline-runner
